### ISSUE TITLE
Pixel Overflow

### ISSUE THREAD

**Issue by anshulkhilrani** [neddstarkk/skybeat-music-player#3]
Pixel overflow warning occurs on the following pages:
1. _New releases for you_ widget on **Explore page**.
2. _Favourites_ widget on the **Profile Page**.
3. Multiple places on the **Settings Page**.

**Comment by neddstarkk** [comment]
Created Pull Request #4 to introduce the class SizeConfig. I've refactored some of the pages, but not all. Please review whether this when applied everywhere, would resolve this issue or not.
